# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Docker build
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -t codesoom-cicd .
          docker tag codesoom-cicd dngwoodo/codesoom-cicd:${GITHUB_SHA:7}
          docker push dngwoodo/codesoom-cicd:${GITHUB_SHA:7}
      - name: Deploy
        uses: applyboy/ssh-action@master
        with:
          host: ec2-13-58-254-109.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull dngwoodo/codesoom-cicd:${hash}
            docker tag dngwoodo/codesoom-cicd:${hash} codesoom-cicd
            docker stop server
            docker run --rm -d -p 3000:3000 --name server codesoom-cicd
